import { providerMeta } from './market-data-quality.js';
const BASE = 'https://www.deribit.com/api/v2';
const n = v => { const x = Number(v); return Number.isFinite(x) ? x : null; };
const envNum = (name, d) => { const x = Number(process.env[name]); return Number.isFinite(x) && x > 0 ? x : d; };

export function parseDeribitInstrument(i, { now = Date.now() } = {}) { return { instrumentName: i.instrument_name, expiryTimestamp: i.expiration_timestamp, daysToExpiry: (i.expiration_timestamp - now) / 86400000, strike: n(i.strike), optionType: i.option_type, isActive: Boolean(i.is_active) }; }
export function selectExpiries(instruments, { maxCount = envNum('OPTIONS_EXPIRY_COUNT', 3), now = Date.now() } = {}) { return [...new Set(instruments.filter(i => i.isActive && i.expiryTimestamp > now).map(i => i.expiryTimestamp).sort((a,b)=>a-b))].slice(0, maxCount); }
export function filterStrikesAroundUnderlying(instruments, underlying, { rangePct = envNum('OPTIONS_STRIKE_RANGE_PCT', 15) } = {}) { const lo = underlying * (1 - rangePct / 100), hi = underlying * (1 + rangePct / 100); return instruments.filter(i => i.strike != null && i.strike >= lo && i.strike <= hi); }
export async function mapWithConcurrency(items, limit, mapper) { const out = new Array(items.length); let next = 0, active = 0, maxActive = 0; await new Promise((resolve, reject) => { const launch = () => { if (next >= items.length && active === 0) return resolve(); while (active < limit && next < items.length) { const idx = next++; active++; maxActive = Math.max(maxActive, active); Promise.resolve(mapper(items[idx], idx, active)).then(v => { out[idx]=v; active--; launch(); }, reject); } }; launch(); }); out.maxActive = maxActive; return out; }
export function parseDeribitTicker(t, instrument) { const greeks = t.greeks ?? {}; const stats = t.stats ?? {}; return { instrumentName: t.instrument_name ?? instrument.instrumentName, expiryTimestamp: instrument.expiryTimestamp, daysToExpiry: instrument.daysToExpiry, strike: instrument.strike, optionType: instrument.optionType, underlyingPrice: n(t.underlying_price), bidPrice: n(t.best_bid_price), askPrice: n(t.best_ask_price), markPrice: n(t.mark_price), bidIv: n(t.bid_iv), askIv: n(t.ask_iv), markIv: n(t.mark_iv), delta: n(greeks.delta), gamma: n(greeks.gamma), vega: n(greeks.vega), theta: n(greeks.theta), openInterest: n(t.open_interest), volume24h: n(stats.volume) }; }
function validIv(o) { return o && o.markIv != null && o.markIv > 0 && o.delta != null; }
function interpByDelta(options, target, type) { const vals = options.filter(o => o.optionType === type && validIv(o)).sort((a,b)=>a.delta-b.delta); if (!vals.length) return { iv:null, method:'unavailable', instrumentNames:[], warning:`missing ${type} 25-delta side` }; let lo=null, hi=null; for (const o of vals) { if (o.delta <= target) lo=o; if (o.delta >= target && !hi) hi=o; } if (lo && hi && lo !== hi) { const w=(target-lo.delta)/(hi.delta-lo.delta); return { iv: lo.markIv + w*(hi.markIv-lo.markIv), method:'linear-delta-interpolation', instrumentNames:[lo.instrumentName, hi.instrumentName] }; } const near = vals.reduce((a,b)=> Math.abs(b.delta-target)<Math.abs(a.delta-target)?b:a); return { iv: near.markIv, method:'nearest-delta fallback', instrumentNames:[near.instrumentName], warning:'delta bracket unavailable; used nearest valid delta' }; }
export function calculateExpiryAnalytics(options, { now = Date.now() } = {}) { const warnings=[]; const underlying = options.find(o=>o.underlyingPrice)?.underlyingPrice ?? null; const withIv = options.filter(o=>o.markIv != null && o.markIv > 0); const atmOption = underlying == null || !withIv.length ? null : withIv.reduce((a,b)=>Math.abs(b.strike-underlying)<Math.abs(a.strike-underlying)?b:a); if (!atmOption) warnings.push('ATM IV unavailable'); const call = interpByDelta(options, 0.25, 'call'); const put = interpByDelta(options, -0.25, 'put'); if (call.warning) warnings.push(call.warning); if (put.warning) warnings.push(put.warning); const atmIv = atmOption?.markIv ?? null; const riskReversal25d = call.iv != null && put.iv != null ? call.iv - put.iv : null; const butterfly25d = call.iv != null && put.iv != null && atmIv != null ? ((call.iv + put.iv)/2) - atmIv : null; return { calculationTimestamp: new Date(now).toISOString(), sourceTimestamp: new Date(now).toISOString(), underlyingPrice: underlying, atm: { strike: atmOption?.strike ?? null, iv: atmIv, method: atmOption ? 'nearest-strike' : 'unavailable', instrumentName: atmOption?.instrumentName ?? null }, call25Delta: call, put25Delta: put, riskReversal25d, butterfly25d, ivUnits: 'percentage points', warnings }; }
export async function fetchDeribitOptions({ fetchImpl = fetch, signal, now = Date.now(), expiryCount = envNum('OPTIONS_EXPIRY_COUNT',3), strikeRangePct = envNum('OPTIONS_STRIKE_RANGE_PCT',15), maxConcurrency = envNum('OPTIONS_MAX_CONCURRENCY',8) } = {}) { const instUrl = `${BASE}/public/get_instruments?currency=BTC&kind=option&expired=false`; const ir = await fetchImpl(instUrl, { signal }); if (!ir.ok) throw new Error(`Deribit instruments HTTP ${ir.status}`); const raw = (await ir.json()).result; const instruments = raw.map(i=>parseDeribitInstrument(i,{now})); const expiries = selectExpiries(instruments,{maxCount:expiryCount,now}); let selected = instruments.filter(i=>expiries.includes(i.expiryTimestamp)); const underlying = selected.find(Boolean)?.strike ?? 0; const midStrike = selected.map(i=>i.strike).filter(Boolean).sort((a,b)=>a-b)[Math.floor(selected.length/2)] ?? underlying; selected = filterStrikesAroundUnderlying(selected, midStrike, { rangePct: strikeRangePct }); const tickers = await mapWithConcurrency(selected, maxConcurrency, async inst => { const r = await fetchImpl(`${BASE}/public/ticker?instrument_name=${encodeURIComponent(inst.instrumentName)}`, { signal }); if (!r.ok) throw new Error(`Deribit ticker HTTP ${r.status}`); return parseDeribitTicker((await r.json()).result, inst); }); const byExpiry = expiries.map(expiryTimestamp => { const contracts = tickers.filter(t=>t.expiryTimestamp===expiryTimestamp); return { expiryTimestamp, expiry: new Date(expiryTimestamp).toISOString(), daysToExpiry: contracts[0]?.daysToExpiry ?? null, contracts, analytics: calculateExpiryAnalytics(contracts,{now}) }; }); return { ...providerMeta({ source:'Deribit', asOf: now, receivedAt: now, status: byExpiry.length?'live':'unavailable', method:'public get_instruments + bounded public/ticker requests', reason: byExpiry.length?null:'No active BTC option expiries selected', now }), currency:'BTC', expiries: byExpiry, config:{ expiryCount, strikeRangePct, maxConcurrency }, ivUnits:'percentage points' }; }
